import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import UpperNavbar from "@/components/upper-navbar";
import ScrollToTop from "@/components/scroll-to-top";

const roboto = Roboto({ weight: '700', subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className}`}
        data-new-gr-c-s-check-loaded="14.1214.0"
        data-gr-ext-installed=""
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UpperNavbar />
          <Navbar />
          <main className="min-h-screen mx-auto">
            {children}
            <ScrollToTop />
          </main>
          <footer className="border-t backdrop:blur py-9 supports-[backdrop-filter]:bg-background/60">
            <div className="container mx-auto px-4 text-center text-white">
              <p className="text-[#221b68]">© {new Date().getFullYear()} <a href="#" className="text-[#6930c3]">AK Web Developers</a>. All rights reserved.</p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
